/**
 * @file tkl_flash.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_flash.h"
#include "tuya_error_code.h"
#include "esp_partition.h"
#include "esp_err.h"
#include "esp_log.h"

/* TODO: need to consider whether to use locks at the TKL layer*/
#define PARTITION_SIZE         (1 << 12) /* 4KB */
#define FLH_BLOCK_SZ            PARTITION_SIZE

//key
#define SIMPLE_FLASH_KEY_ADDR 0x0 /* offset of tuya data partition */

//KV
#define SIMPLE_FLASH_START (SIMPLE_FLASH_KEY_ADDR + PARTITION_SIZE)
#define SIMPLE_FLASH_SIZE 0x8000 // 32K

//UF
#ifndef UF_PARTITION_NUM
#define UF_PARTITION_NUM     1
#endif

#ifndef UF_PARTITION_START
#define UF_PARTITION_START  0x26C000
#endif

#ifndef UF_PARTITION_SIZE
#define UF_PARTITION_SIZE   0x134000
#endif

#if defined(KV_PROTECTED_ENABLE) && (KV_PROTECTED_ENABLE==1)
#define SIMPLE_FLASH_KV_PROTECTED_START (UF_PARTITION_START + UF_PARTITION_SIZE)
#define SIMPLE_FLASH_KV_PROTECTED_SIZE 0x1000
#endif

#ifndef TUYA_PARTITION_SUBTYPE
#define TUYA_PARTITION_SUBTYPE ESP_PARTITION_SUBTYPE_DATA_SPIFFS
#endif

#ifndef TUYA_PARTITION_LABEL
#define TUYA_PARTITION_LABEL "spiffs"
#endif

#ifndef GET_TUYA_DATA_PARTITION
#define GET_TUYA_DATA_PARTITION() esp_partition_find_first(ESP_PARTITION_TYPE_DATA, TUYA_PARTITION_SUBTYPE, TUYA_PARTITION_LABEL)
#endif

typedef struct {
    char *uuid;
    char *authkey;
} tuya_iot_license_t;
// --- END: user defines and implements ---

/**
* @brief read flash
*
* @param[in] addr: flash address
* @param[out] dst: pointer of buffer
* @param[in] size: size of buffer
*
* @note This API is used for reading flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_read(uint32_t addr, uint8_t *dst, uint32_t size)
{
    // --- BEGIN: user implements ---
    const esp_partition_t *partition;

    if (NULL == dst) {
        return OPRT_INVALID_PARM;
    }
    
    partition = GET_TUYA_DATA_PARTITION();
    if (NULL == partition) {
        ESP_LOGE("FL", "PARTITION NOT FOUND. label: %s. address: 0x%X", partition->label, (unsigned int)partition->address);
        return OPRT_COM_ERROR;
    }

    esp_err_t err = esp_partition_read(partition, (unsigned int)(addr - partition->address), dst, size);
    if (ESP_OK != err) {
        ESP_LOGE("FL", "esp_partition_read NOT ESP_OK 0x%X: %s. label: %s. address: 0x%X / 0x%X. dst: 0x%X %d / %d", 
            err, esp_err_to_name(err), 
            partition->label, 
            (unsigned int)addr, (unsigned int)partition->address, 
            (unsigned int)dst, 
            (unsigned int)size, (unsigned int)sizeof(dst)
        );
        
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief write flash
*
* @param[in] addr: flash address
* @param[in] src: pointer of buffer
* @param[in] size: size of buffer
*
* @note This API is used for writing flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_write(uint32_t addr, const uint8_t *src, uint32_t size)
{
    // --- BEGIN: user implements ---
    const esp_partition_t *partition;

    if (NULL == src) {
        return OPRT_INVALID_PARM;
    }
    
    partition = GET_TUYA_DATA_PARTITION();
    if (NULL == partition) {
        return OPRT_COM_ERROR;
    }

    if (ESP_OK != esp_partition_write(partition, (unsigned int)(addr - partition->address), src, size)) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief erase flash
*
* @param[in] addr: flash address
* @param[in] size: size of flash block
*
* @note This API is used for erasing flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_erase(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    const esp_partition_t *partition;

    partition = GET_TUYA_DATA_PARTITION();
    if (NULL == partition) {
        return OPRT_COM_ERROR;
    }

    if (ESP_OK != esp_partition_erase_range(partition, (unsigned int)(addr - partition->address), size)) {
        return OPRT_COM_ERROR;
    }


    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief lock flash
*
* @param[in] addr: lock begin addr
* @param[in] size: lock area size
*
* @note This API is used for lock flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_lock(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief unlock flash
*
* @param[in] addr: unlock begin addr
* @param[in] size: unlock area size
*
* @note This API is used for unlock flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_unlock(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief get flash information
*
* @param[out] info: the description of the flash
*
* @note This API is used to get description of storage.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_get_one_type_info(TUYA_FLASH_TYPE_E type, TUYA_FLASH_BASE_INFO_T* info)
{
    // --- BEGIN: user implements ---
    if ((type > TUYA_FLASH_TYPE_MAX) || (info == NULL)) {
        return OPRT_INVALID_PARM;
    }
    switch (type) {
        case TUYA_FLASH_TYPE_UF:
            info->partition_num = 1;
            info->partition[0].block_size =  PARTITION_SIZE;
            info->partition[0].start_addr = UF_PARTITION_START;
            info->partition[0].size = UF_PARTITION_SIZE;
            break;
       case TUYA_FLASH_TYPE_KV_DATA:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_START;
            info->partition[0].size = SIMPLE_FLASH_SIZE;
            break;
       case TUYA_FLASH_TYPE_KV_KEY:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_KEY_ADDR;
            info->partition[0].size = FLH_BLOCK_SZ;
            break;
#if defined(KV_PROTECTED_ENABLE) && (KV_PROTECTED_ENABLE==1)
        case TUYA_FLASH_TYPE_KV_PROTECT:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_KV_PROTECTED_START;
            info->partition[0].size = SIMPLE_FLASH_KV_PROTECTED_SIZE;
            break;
#endif
        default:
            return OPRT_INVALID_PARM;
            break;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief tuya_iot_license_read
*
* @param[in] license: iot license struct pointer
*
* @note This API is used for read license .
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
int tuya_iot_license_read(tuya_iot_license_t *license)
{
    return OPRT_NOT_SUPPORTED;
}